# Generated by Django 3.1.3 on 2021-10-23 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255)),
                ('article_browse', models.CharField(max_length=255)),
                ('article_image', models.CharField(max_length=200)),
                ('article_hits', models.IntegerField(default=0)),
                ('article_content', models.TextField()),
                ('article_time', models.DateTimeField(auto_now_add=True)),
                ('article_is_delete', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_image', models.CharField(max_length=200)),
                ('book_author', models.CharField(max_length=200)),
                ('book_type', models.CharField(max_length=200)),
                ('book_brief', models.TextField()),
                ('book_is_end', models.CharField(max_length=200)),
                ('book_newest_time', models.CharField(max_length=200)),
                ('book_newest', models.CharField(max_length=200)),
                ('book_is_show', models.IntegerField(default=0)),
                ('book_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('Article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.article')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_add', models.CharField(max_length=200)),
                ('image_type', models.CharField(max_length=200)),
                ('image_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_img', models.CharField(max_length=200)),
                ('music_url', models.CharField(max_length=200)),
                ('music_name', models.CharField(max_length=200)),
                ('music_type', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Music',
            },
        ),
        migrations.CreateModel(
            name='ShowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=100)),
                ('user_img', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
                ('user_motto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ShowUser',
            },
        ),
        migrations.CreateModel(
            name='TemporaryMotto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporaryMotto_ip', models.CharField(max_length=200)),
                ('temporaryMotto_name', models.CharField(default='', max_length=200)),
                ('temporaryMotto_time', models.DateTimeField(auto_now_add=True)),
                ('temporaryMotto_last', models.DateTimeField(auto_now=True)),
                ('temporaryMotto_email', models.CharField(default='', max_length=200)),
                ('temporaryMotto_img', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'TemporaryMotto',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(default='用户9k8GMCAW', max_length=20, null=True)),
                ('user_password', models.CharField(max_length=100)),
                ('user_creation_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Fabulous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('Article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.article')),
                ('TemporaryMotto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.temporarymotto')),
            ],
            options={
                'db_table': 'Fabulous',
            },
        ),
        migrations.CreateModel(
            name='CommentSecondary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('Article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.article')),
                ('Comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.comment')),
                ('TemporaryMotto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.temporarymotto')),
            ],
            options={
                'db_table': 'CommentSecondary',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='TemporaryMotto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.temporarymotto'),
        ),
        migrations.CreateModel(
            name='BrowseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browseRecord_partition', models.CharField(max_length=30)),
                ('browseRecord_time', models.DateTimeField(auto_now_add=True)),
                ('TemporaryMotto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DataBase.temporarymotto')),
            ],
            options={
                'db_table': 'BrowseRecord',
            },
        ),
    ]
