# Generated by Django 3.2.9 on 2021-11-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_name', models.CharField(max_length=200)),
                ('friend_url', models.CharField(max_length=200)),
                ('friend_img', models.CharField(max_length=200)),
                ('friend_introduce', models.CharField(max_length=200)),
                ('friend_time', models.DateTimeField(auto_now_add=True)),
                ('friend_is_show', models.IntegerField(default=0)),
                ('friend_invalid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Friend',
            },
        ),
        migrations.AddField(
            model_name='showuser',
            name='user_qq',
            field=models.CharField(default='2521575963', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_username',
            field=models.CharField(default='用户iLKzw4cu', max_length=20, null=True),
        ),
    ]
